spring:
  redis:
    host: ${REDIS_HOST}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

weather:
  api:
    key: ${WEATHER_API_KEY}
